### ISSUE TITLE
Error when I enter the docker command

### ISSUE THREAD

**Issue by Vikasnaga9** [in-pyjama/c-ninja-listings#15]
<img width="858" alt="image" src="https://github.com/inpyjama/c-ninja-listings/assets/145089743/51dd3b06-b19a-4047-847b-b714a5cc4f2f">

I have tried entering the command you mentioned and it does not work should I be doing any kind of setting on the docker side??

I see that c-ninja is running on Docker 
<img width="1396" alt="image" src="https://github.com/inpyjama/c-ninja-listings/assets/145089743/ec3ebaf0-531d-4595-bee6-cea2b12b4dfa">

**Comment by streetdogg** [comment]
@Vikasnaga9  -

Can you try the following sequence of commands:
```
bash
```
followed by
```
c-ninja
```

The alias is added to the `.bashrc`, so changing the shell should solve this issue.

**Comment by Vikasnaga9** [comment]
<img width="605" alt="image" src="https://github.com/inpyjama/c-ninja-listings/assets/145089743/d018c7a7-510d-4b77-a2ca-3a12063671f5">
 

Looks like it worked Thank you for the Prompt response 👍🏽💯

**Comment by Vikasnaga9** [comment]
Resolved
