### ISSUE TITLE
username and hostname of the has been changed in terminal in vscode 

### ISSUE THREAD

**Issue by lsrujan** [in-pyjama/c-ninja-listings#16]
![image](https://github.com/inpyjama/c-ninja-listings/assets/107785851/453ced40-f7f3-41d0-b6cf-13cdcb790f08)
[](url)

**Comment by streetdogg** [comment]
@lsrujan - Yes, that is expected. 

VSCode will be connected to the docker container which has the Linux image and all the tools required to do the experiments. The password for the `c-ninja` user is `c` (if you need it for anything in the future)!
