### ISSUE TITLE
bash: riscv64-unknown-elf-gcc: command not found

### ISSUE THREAD

**Issue by Mohan-saini** [in-pyjama/c-ninja-listings#17]
I followed all the steps mentioned here, as docker I cannot install on my linux machine due to permission issues
https://github.com/riscv-collab/riscv-gnu-toolchain

I see in bin directory, this is present
----
 riscv64-unknown-elf-gcc 
--------

But even after running it there, it shows command not found. Any response will be appriciated

thanks

**Comment by streetdogg** [comment]
Can you share some screenshots? Also, this looks like a deviation from the steps we use. We create a docker container and work within that.

**Comment by Mohan-saini** [comment]
I tried creating docker container as mentioned on your github page but getting below error
![image](https://github.com/inpyjama/c-ninja-listings/assets/33348228/7946ed9c-00ab-42f7-a497-78d4e26e861e)

I searched a lot on internet to resolve it but not working, this is coming always

**Comment by streetdogg** [comment]
Can you help with details of the OS and version you are using, I can try to reproduce this locally. Also, did you try steps listed here?
- https://github.com/inpyjama/c-ninja-listings#1211-update-apt-sources

**Comment by Mohan-saini** [comment]
Hi piyush.. I tried exact same steps as on your github.. Even I followed the youtube video for setting up lab environment but failing.

I am on ubuntu 16.04.7

Please help to check if we can get any fix

**Comment by streetdogg** [comment]
`16.04.7` looks too old. While I spend time figuring out what can be done here. In the meantime, to unblock you can you try using the GitHub Codespace? 

1. I made a video explaining how to go about doing it:
    1. https://www.youtube.com/watch?v=MBL3wJp7cAA

**Comment by Mohan-saini** [comment]
Yeah.. I tried code space and its working.

Thanks

**Comment by streetdogg** [comment]
@Mohan-saini - Can this issue be closed?

**Comment by Mohan-saini** [comment]
@streetdogg sure. , using code space for now and its working
Thanks

**Comment by Mohan-saini** [comment]
Thanks
