### ISSUE TITLE
Issue in make debug terminal

### ISSUE THREAD

**Issue by PranabNandy** [in-pyjama/c-ninja-listings#18]
I am able to successfully close the **make gdb** terminal
but when I am trying to close **make debug** terminal with `ctrl+a  ` followed by ` x `, nothing is happening 
![Screenshot from 2023-10-26 10-11-17](https://github.com/inpyjama/c-ninja-listings/assets/34576104/560bb7ec-7425-47f0-81b3-e5b997cb6126)

**Comment by streetdogg** [comment]
`ctrl+a x` has been consistently working for me. There are some ways listed here too: https://superuser.com/questions/1087859/how-to-quit-the-qemu-monitor-when-not-using-a-gui

If not, I recommend killing the qemu process from another terminal. Try these:

1. `ps -aux | grep qemu`
    1. Look for `qemu-system-riscv32 -S -M virt -nographic -bios none -kernel main.elf -gdb tcp::1234` and copy the process number.
1. `kill <process id>`

-----

See if attached screenshot is useful -
![Xnip2023-10-28_18-07-54](https://github.com/inpyjama/c-ninja-listings/assets/2120983/856cb6e8-9394-4395-96ff-ee626f6f5789)

**Comment by PranabNandy** [comment]
Thank you for the information.

Another problem now I am facing like CodeSpace is not opening now

**Comment by streetdogg** [comment]
@PranabNandy - Sure. I'd really appreciate it if you could add some data that makes it easy to help. Be detailed about the steps to reproduce the issue.

**Comment by PranabNandy** [comment]
Previously I was able to open the Code Space
Now only this screen is coming 
No other  thing is happening for me 
![Screenshot from 2023-10-29 16-31-30](https://github.com/inpyjama/c-ninja-listings/assets/34576104/709ef450-94c5-4867-bb4d-d89339ad892f)

**Comment by PranabNandy** [comment]
When I am trying to follow the steps to set up the lab in linux machine
I am not getting the same colour terminal as you are showing the video.
when I am executing this command
`sudo chown -R c-ninja .`
I am writing sudo user password still it is not accepting 
![Screenshot from 2023-10-29 16-39-21](https://github.com/inpyjama/c-ninja-listings/assets/34576104/534a7c3c-67b2-40c4-a723-982932440deb)

**Comment by streetdogg** [comment]
> Previously I was able to open the Code Space Now only this screen is coming No other thing is happening for me ![Screenshot from 2023-10-29 16-31-30](https://user-images.githubusercontent.com/34576104/278866420-709ef450-94c5-4867-bb4d-d89339ad892f.png)

This usually takes some time. But it should show some output.

> When I am trying to follow the steps to set up the lab in linux machine I am not getting the same colour terminal as you are showing the video. when I am executing this command `sudo chown -R c-ninja .` I am writing sudo user password still it is not accepting ![Screenshot from 2023-10-29 16-39-21](https://user-images.githubusercontent.com/34576104/278866800-534a7c3c-67b2-40c4-a723-982932440deb.png)

What password did you use? The password to be used is `c`. The terminal colors for you seem different because your terminal theme may be different. That is alright. Can you try using `c` as the password for the `c-ninja` user?

**Comment by PranabNandy** [comment]
### This usually takes some time. But it should show some output.
- It's been like 30 mins I opened the window but it stuck to the same screen


### What password did you use? The password to be used is c. The terminal colors for you seem different because your terminal theme may be different. That is alright. Can you try using c as the password for the c-ninja user?
- Actually I did not use the password `c`. Now it is working 


Thank you

**Comment by PranabNandy** [comment]
One more thing I would like to mention, while executing this command `wget -P ~ https://git.io/.gdbinit`, I was facing this issue

```
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 49.44.79.236, ::ffff:49.44.79.236
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.44.79.236|:443...
```

I followed this Link to resolve it
 https://www.debugpoint.com/failed-connect-raw-githubusercontent-com-port-443/

But the ip address `185.199.108.133 `they are using is not working for me

Then I checked the IP address in the video which is `185.199.111.133`, it worked for me.

**Comment by streetdogg** [comment]
that's odd, but I am glad it's working for you now. Would you say we can conclude this issue?

**Comment by PranabNandy** [comment]
In conclusion, I would say Codespace is not opening for me. Even though it opened for the first day.

I installed the Docker Image in my local machine and everything is working fine there.

**Comment by streetdogg** [comment]
can you delete and recreate the codespace? I was under the impression that it would work for all. Would really appreciate your help with more data on this, it might help others who don't have a powerful machine and high-speed internet.

**Comment by PranabNandy** [comment]
I deleted the codespace and recreated it but still, it did not open for me.

I even deleted the repo and forked it again still, the same problem is there.

**Comment by streetdogg** [comment]
Very strange. I think it would be good to take up with the GitHub support team. This looks beyond us at the moment.

**Comment by PranabNandy** [comment]
Ok Sure.
Thank you for your kind support. 
I think we can close this issue.
