### ISSUE TITLE
c-ninja cmd not working in windows 

### ISSUE THREAD

**Issue by thenameismadhu** [in-pyjama/c-ninja-listings#20]
i could't get docker running in background and get the c-ninja command in windows comd prompt.

**Comment by streetdogg** [comment]
@thenameismadhu - Could you please share more details, any screenshots, OS versions etc?

The best environment to work in is the GitHub's Codespace. The guide on how to go about doing it is here - https://www.youtube.com/watch?v=MBL3wJp7cAA&list=PLFt5JBAXXlQow0PLTdqvaiIUMRa71VQHl&index=1

**Comment by sreemoorthy** [comment]
you can run the c-ninja.bat file from c-ninja-listings folder or run the command  ./c-ninja.bat from the listings folder

**Comment by streetdogg** [comment]
@thenameismadhu - please use the `c-ninja.bat` file to launch the docker. Thanks for helping out, @sreemoorthy!!
