### ISSUE TITLE
bash setup.sh fails to complete

### ISSUE THREAD

**Issue by g-nikolovski** [in-pyjama/c-ninja-listings#21]
Hello,
While trying to execute bash setup.sh i encounter the following problem:

` => ERROR [6/9] RUN apt-get install --no-install-recommends -y   ca-certificates   sudo   gdb-multiarch   gcc-riscv64-unknown-elf   binutils-common   make   curl  4.2s
------                                                                                                                                                                  
 > [6/9] RUN apt-get install --no-install-recommends -y   ca-certificates   sudo   gdb-multiarch   gcc-riscv64-unknown-elf   binutils-common   make   curl   git-core   wget   nano   ssh   tree   less   build-essential   python3   python3-dev   binutils   make   binutils-riscv64-linux-gnu   qemu-system-riscv32   zsh   xxd   strace   man:                                                                                                                                                                      
0.809 Reading package lists...                                                                                                                                          
3.514 Building dependency tree...
3.883 Reading state information...
4.093 E: Unable to locate package gcc-riscv64-unknown-elf
4.093 E: Unable to locate package qemu-system-riscv32`

It looks like it can not locate gcc-riscv64-unknown-elf and qemu-system-riscv32.
I am running on Ubuntu 18.04.
Do you have any idea what could be the problem here, might it be the Ubuntu version, the fact that i didn't install the Docker Desktop (i don't think the these should pose any problem by the way) or is it something else of which i am not aware?

Thank you

**Comment by g-nikolovski** [comment]
I fixed it on my machine by replacing
`FROM ubuntu:latest` inside Dockerfile with: `FROM ubuntu:22.04`
I guess you can close this.

**Comment by streetdogg** [comment]
@g-nikolovski - Thank you for the investigation and the solution. 

The best environment to work in is the GitHub's Codespace. The guide on how to go about doing it is here - https://www.youtube.com/watch?v=MBL3wJp7cAA&list=PLFt5JBAXXlQow0PLTdqvaiIUMRa71VQHl&index=1
