### ISSUE TITLE
Setup no working properly on macbook

### ISSUE THREAD

**Issue by sunix01** [in-pyjama/c-ninja-listings#23]
![Screen Shot 2023-11-21 at 6 04 46 PM](https://github.com/inpyjama/c-ninja-listings/assets/84481585/4726de61-2fbe-4adc-af6a-dd6019822b4e)
I tried this setup on my MacBook but it not creating the container please help me out

**Comment by streetdogg** [comment]
Could you help with the command that you executed to start the setup process?

**Comment by nivasvadapalli** [comment]
I tried today and its working fine to me
