### ISSUE TITLE
error in running setup.bat

### ISSUE THREAD

**Issue by SravanKumar-M** [in-pyjama/c-ninja-listings#26]
![Screenshot 2023-12-25 221927](https://github.com/inpyjama/c-ninja-listings/assets/76786088/a570003f-f670-4554-a722-96253cd08603)
![Screenshot 2023-12-25 221809](https://github.com/inpyjama/c-ninja-listings/assets/76786088/e78e61cb-87eb-48f9-82e1-b41d01b9fb44)
![Screenshot 2023-12-25 221741](https://github.com/inpyjama/c-ninja-listings/assets/76786088/8caefc50-b8c3-4ee7-8083-2d1e315ff75b)
I'm getting these errors
I tried doing it 5 times 3 times got the error in [6/9] and 2 time at [7/9]

**Comment by SravanKumar-M** [comment]
NOW it ran fine, everything is running fine

**Comment by streetdogg** [comment]
looks like this is resolved. closing the issue.
