### ISSUE TITLE
Not able to complete setup in MAC.. step #2 is failing

### ISSUE THREAD

**Issue by chakry123** [in-pyjama/c-ninja-listings#29]
![Screenshot 2024-05-01 at 2 41 27 PM](https://github.com/inpyjama/c-ninja-listings/assets/96410170/e9da7058-1052-455d-bf19-e9be8e5be7e3)

**Comment by streetdogg** [comment]
@chakry123 - I just updated the repo: https://github.com/inpyjama/c-ninja-listings/commit/22e0dfa0d47741c3db35e82087d780dc8228dc79. After this change, things are working well for me on my Mac. Can you pull the latest changes and try again?

**Comment by chakry123** [comment]
Thanks, with the fix , it is working now.
