### ISSUE TITLE
vs code error

### ISSUE THREAD

**Issue by Batuk-sud** [in-pyjama/c-ninja-listings#34]
This is what i am getting in vs code . Kindly help
![Screenshot 2024-06-17 003143](https://github.com/inpyjama/c-ninja-listings/assets/172805317/a978b5bc-8211-4f2e-b2c9-f02d0ba1e77c)

**Comment by anjula544** [comment]
I also have this problem.

**Comment by manthan-juvekar** [comment]
even i do have the same exact problem

**Comment by streetdogg** [comment]
From the terminal, can you check the permissions on the directory? look like you might have to do `chmod` and change the permissions so VSCode can write into it.

**Comment by vishy312** [comment]
On windows:
1 - Open c-ninja-listings folder in vs code
2 - It'll ask for authorization. Click Ok.
3 - Now run dev container

This is what worked for me

**Comment by streetdogg** [comment]
Thank you for fielding this, @vishy312 🙌
