### ISSUE TITLE
 => ERROR [6/6] RUN yes | unminimize

### ISSUE THREAD

**Issue by rohitalate** [in-pyjama/c-ninja-listings#38]
Hello Team ,
I am getting below error can you please help here to resolve...

is anyone faced this issue ???

![image](https://github.com/user-attachments/assets/b52676cb-6674-4939-9afd-62e000901b83)

**Comment by rohitalate** [comment]
@streetdogg @therustyengineer

**Comment by Prakasia** [comment]
Hi @rohitalate,
I also had this error I resolved the issue by adding unminimize to the install package :: 
In c-ninja-listing folder there is a 'Dockerfile' file, add unminimize to the list of packages in the Run apt-get-install. 
This worked for me

**Comment by rehannasar2002** [comment]
Hi @Prakasia,
Thanks for the tip, had the same issue as @rohitalate.
After adding unminimize, worked perfectly!

**Comment by streetdogg** [comment]
Thank you for feilding this @Prakasia! I added the change and this error should be resolved for all.
