### ISSUE TITLE
Permission Denied Error when Running 'make' in '/Document/test' directory

### ISSUE THREAD

**Issue by EkenoSamson** [in-pyjama/c-ninja-listings#5]
I'm encountering an issue when trying to run 'make' in the /Document/test directory while following the YouTube video(C-Language: C Ninja, in Pyjama! - #0. Lab Setup!) at [12:44](https://www.youtube.com/watch?v=KJtUWnJr254&t=764s)

```
c-ninja@c-ninja-linux ~/Documents/test
% make
riscv64-unknown-elf-gcc -O0 -ggdb -nostdlib -march=rv32i -mabi=ilp32 -Wl,-Tmain.ld main.s -o main.elf
/usr/lib/riscv64-unknown-elf/bin/ld: cannot open output file main.elf: Permission denied
collect2: error: ld returned 1 exit status
```

I have also attached the screen of my terminal.
![Screenshot from 2023-09-17 12-21-06](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/fcdb7ee5-623c-4048-8f2c-9a89dd21f035)

Here are the details when I run ``` uname -a ``` in my terminal.
![Screenshot from 2023-09-17 12-26-32](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/a704a731-1393-49ba-8950-1784ac3e88a0)

I am using ubuntu.
![image](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/f2ce26a5-c6ac-4cfa-aacc-fdfef2853806)

**Comment by EkenoSamson** [comment]
When I use ```sudo make``` and provide the required password, it successfully generates the desired output. It appears that this resolves the issue.
![Screenshot from 2023-09-17 12-35-40](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/e9673cbc-008f-4e1b-8504-c89508b0cebf)

**Comment by EkenoSamson** [comment]
Using the terminal in the Vscode after connecting using the Remote Explorer.
![Screenshot from 2023-09-17 13-08-04](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/18a18b02-d4a7-49c4-a722-b58200e07708)

**Comment by streetdogg** [comment]
Thank you, @EkenoSamson for opening the issue!

It looks to me that the `c-ninja` user doesn't have the **write** access to the path `~/Documents/test`. Could you help run the following command and share the output?

```
ls -al
```

Unfortunately, I did not try the setup on a Linux machine. I will try to reproduce the error on that. In the meantime, can I also request you, to try adding the `c-ninja` user to the `sudo` group using the commands below?

```
sudo usermod -aG sudo c-ninja
```

I am hoping the `make` command will work as expected after this.

**Comment by pankajsys** [comment]
This is happening because while mounting test folder to container's ~/Documents/ directory, user files are being mounted as owned by root while preserving file permissions.
This issue and issue comment will help - https://github.com/moby/moby/issues/3124#issuecomment-104936573

![fileperm](https://github.com/in-pyjama/c-ninja-listings/assets/43030770/c3b54b4d-e2de-4c38-9acd-553e0fca5b9f)

The permissions for test folder indicate write permissions for others are not enabled hence not allowing other users to create output file main.elf

Please run to give other users write access in the folder

> `sudo chmod +007 ../test/`

Post that, again run make and we should be able to see the o/p


![done](https://github.com/in-pyjama/c-ninja-listings/assets/43030770/f87afcde-1321-45c3-bc7a-b4f400de3fed)

**Comment by EkenoSamson** [comment]
the following is the output after I ran ```ls -la``` command.
![Screenshot from 2023-09-17 17-30-20](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/f8ccc1f6-5197-4c13-ae2f-c43a4b15a87b)

After adding c-ninja to the sudo group using ```sudo usermod -aG sudo c-ninja``` and trying ```make```
![Screenshot from 2023-09-17 17-37-59](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/2c98d309-ad36-44ee-8464-0d8ac9bac7c2)

**Comment by 7022106205** [comment]
![Screenshot from 2023-09-22 17-18-58](https://github.com/in-pyjama/c-ninja-listings/assets/75203145/ac46e6f6-9f84-44eb-bc2c-216c58af51c9)


I tried entering my Ubuntu Login Password, but its not taking. Is there any different password?

**Comment by streetdogg** [comment]
@7022106205: The password for the `c-ninja` user is `c`. Your login password won't work within the docker image 😊

Let us know if this helped.

**Comment by 7022106205** [comment]
> @7022106205: The password for the `c-ninja` user is `c`. Your login password won't work within the docker image 😊
> 
> Let us know if this helped.
It worked, thank you.
I

**Comment by 7022106205** [comment]
> @7022106205: The password for the `c-ninja` user is `c`. Your login password won't work within the docker image 😊
> 
> Let us know if this helped.

It worked, thank you.

**Comment by streetdogg** [comment]
@EkenoSamson: 

Can you try the following and see if this resolves the `permission` issue? I tried this locally on an Ubuntu machine and seemed to work well -
```
c-ninja@c-ninja-linux ~/Documents
% sudo chown -R c-ninja .
```

I am able to execute the `make` command without `sudo` as below:

![docker-0001](https://github.com/in-pyjama/c-ninja-listings/assets/2120983/7cfe8c8e-7a6b-41a1-825b-c714b631e11e)

**Comment by EkenoSamson** [comment]
@streetdogg
I tried it and it's working. Thank you.
![Screenshot from 2023-10-04 13-57-39](https://github.com/in-pyjama/c-ninja-listings/assets/55789026/4adde08d-65aa-49b5-ab57-c2286cabb5db)

**Comment by streetdogg** [comment]
Awesome! Thanks!
