### ISSUE TITLE
Error in make command in Windows.

### ISSUE THREAD

**Issue by Yuva-Adhithyan** [in-pyjama/c-ninja-listings#7]
![image](https://github.com/in-pyjama/c-ninja-listings/assets/76591922/60cfc420-8d65-4f22-b659-9a2af9d4235e)

**Comment by streetdogg** [comment]
@ Yuva-Adhithyan: Hello! The make command needs to be run from within the docker terminal. From the screenshot, I see that the command was executed from the windows environment.

@freaX22 - was wondering if you have any inputs for this?

**Comment by therustyengineer** [comment]
Can you try these two things

1- launch docker desktop and verify if your container is running or not 

Use the below command 
docker exec -it c-ninja-linux /bin/zsh -c "touch ~/.zshrc; cd /home/c-ninja/Documents; zsh -i"

To launch the container and get linux shell running in docker

Then you should be able to launch make.

If the problem exists can you share screenshot pf your docker-desktop screen

**Comment by streetdogg** [comment]
@Yuva-Adhithyan - Can you confirm if the steps in https://github.com/in-pyjama/c-ninja-listings/issues/7#issuecomment-1732289986 helped?

**Comment by mahussain1** [comment]
For me, https://github.com/inpyjama/c-ninja-listings/issues/7#issuecomment-1732289986 works perfectly well.
